# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch:
    branches: [ $default-branch ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 pubs --count --show-source --statistics
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.2
    - name: Test with pytest
      run: |
        python -m pytest tests --log-level=INFO
    - name: Coverage
      run: |
        coverage run -m pytest tests
    - name: Coverage html
      run: |
        coverage html
        cd htmlcov && tar -zcf ../htmlcov.tar.gz *
    - name: Upload html coverage results
      env:
        USER: ${{ secrets.DOCS_USERNAME }}
        PASS: ${{ secrets.DOCS_PASSWORD }}
      run: |
        curl --data-binary "@htmlcov.tar.gz" -XPUT "https://$USER:$PASS@docs.icecube.aq/api/upload?path=$GITHUB_REPOSITORY/$GITHUB_REF"
        echo "Coverage report available on https://docs.icecube.aq/$GITHUB_REPOSITORY/$GITHUB_REF"
    - name: Coverage Text Report
      run: |
        coverage report -m --fail-under=50
