# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Master tests

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 pubs --count --show-source --statistics
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.2
    - name: Test with pytest
      run: |
        python -m pytest tests --log-level=INFO
    - name: Coverage
      run: |
        coverage run -m pytest tests
    - name: Coverage Text Report
      run: |
        coverage report -m --fail-under=50
